default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: avant-gardelabs_com_development
test:
  <<: *default
  database: avant-gardelabs_com_test
production:
  <<: *default
  database: avant-gardelabs_com_production
